// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYaF5WiNz9MoG8MjlYXYX_-Xi7JWBl-VU',
    appId: '1:529415271397:web:7b2699d4cd81ddb5fc750c',
    messagingSenderId: '529415271397',
    projectId: 'fruit-hub-51083',
    authDomain: 'fruit-hub-51083.firebaseapp.com',
    storageBucket: 'fruit-hub-51083.appspot.com',
    measurementId: 'G-E2HME4KPGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr4XaNVHoK5rmUZ3qxXDLEWytSShULuJU',
    appId: '1:529415271397:android:5064bbf4b79e8de2fc750c',
    messagingSenderId: '529415271397',
    projectId: 'fruit-hub-51083',
    storageBucket: 'fruit-hub-51083.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXOSGx7EDgjspQW2PWinHwpOr6_S9hMkE',
    appId: '1:529415271397:ios:951a85d83ac5b035fc750c',
    messagingSenderId: '529415271397',
    projectId: 'fruit-hub-51083',
    storageBucket: 'fruit-hub-51083.appspot.com',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXOSGx7EDgjspQW2PWinHwpOr6_S9hMkE',
    appId: '1:529415271397:ios:25293e4aa355d7b0fc750c',
    messagingSenderId: '529415271397',
    projectId: 'fruit-hub-51083',
    storageBucket: 'fruit-hub-51083.appspot.com',
    iosBundleId: 'com.example.fruitHub.RunnerTests',
  );
}
